# Generated by Django 5.2.8 on 2025-12-01 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('avg_buy_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buy_date', models.DateField(null=True)),
                ('invested_value', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('gain_loss', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('weight_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_gain_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('day_change', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('day_change_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benchmark', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.benchmarkindex')),
            ],
        ),
    ]
