# Generated by Django 5.2.8 on 2025-12-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField()),
                ('health_score', models.IntegerField()),
                ('diversification_score', models.IntegerField()),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sharpe_ratio', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('return_1d', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('return_ytd', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('alpha', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('beta', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('sector_allocation', models.JSONField(default=dict)),
                ('top_holdings', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invested_value', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
            ],
        ),
    ]
