# Generated by Django 5.2.8 on 2025-12-01 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='portfoliovaluehistory',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['portfolio', '-analysis_date'], name='idx_analysis_pf_date'),
        ),
        migrations.AlterUniqueTogether(
            name='analysisresult',
            unique_together={('portfolio', 'analysis_date')},
        ),
        migrations.AlterUniqueTogether(
            name='portfoliovaluehistory',
            unique_together={('portfolio', 'record_date')},
        ),
    ]
