# Generated by Django 5.2.8 on 2025-12-01 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], default='NSE', max_length=10)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('day_change', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('day_change_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.sector')),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(null=True)),
                ('daily_return', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.stock')),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('close_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_return', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.benchmarkindex')),
            ],
            options={
                'unique_together': {('benchmark', 'trade_date')},
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='idx_stocks_symbol'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector'], name='idx_stocks_sector'),
        ),
        migrations.AddIndex(
            model_name='stockpricehistory',
            index=models.Index(fields=['stock', '-trade_date'], name='idx_price_history_stock_date'),
        ),
        migrations.AddIndex(
            model_name='stockpricehistory',
            index=models.Index(fields=['trade_date'], name='idx_price_history_date'),
        ),
        migrations.AlterUniqueTogether(
            name='stockpricehistory',
            unique_together={('stock', 'trade_date')},
        ),
    ]
